### ISSUE TITLE
Issue with subclasses in widget matching

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/midas#48]
We recently made changes to IceNet/SimpleNIC that changed the NICIO to be a subclass of SerialIO instead of StreamIO. Unfortunately, this caused midas widget mapping to break, because the SerialWidget was matching on SerialIO and all its subclasses, so it mistakenly matched the NICIO with the SerialWidget instead of the SimpleNICWidget. The solution was to change SimSerialIO's matchType function to explicitly return false for NICIO. I'm not sure how exactly this issue could be avoided in the future.

**Comment by davidbiancolin** [comment]
Resolved with new system.
